// Enhanced Multi-Tenant Dashboard - Path Constants
// Generated by setup-paths.ts

export const PATHS = {
  "BASE_DIR": "/Users/nolarose/mcp-tools",
  "CONFIG_DIR": "/Users/nolarose/mcp-tools/config",
  "DATA_DIR": "/Users/nolarose/mcp-tools/data",
  "LOGS_DIR": "/Users/nolarose/mcp-tools/logs",
  "BACKUPS_DIR": "/Users/nolarose/mcp-tools/backups",
  "SNAPSHOTS_DIR": "/Users/nolarose/mcp-tools/snapshots",
  "AUDIT_DIR": "/Users/nolarose/mcp-tools/audit-review",
  "DATABASE": {
    "DEVELOPMENT": "/Users/nolarose/mcp-tools/data/dev-audit.db",
    "STAGING": "/Users/nolarose/mcp-tools/data/staging-audit.db",
    "PRODUCTION": "/Users/nolarose/mcp-tools/data/prod-audit.db",
    "TEST": "/Users/nolarose/mcp-tools/data/test-audit.db"
  },
  "CONFIG": {
    "DEVELOPMENT": "/Users/nolarose/mcp-tools/config/.env.development",
    "STAGING": "/Users/nolarose/mcp-tools/config/.env.staging",
    "PRODUCTION": "/Users/nolarose/mcp-tools/config/.env.production",
    "NGINX": "/Users/nolarose/mcp-tools/config/nginx.conf",
    "DOCKER": "/Users/nolarose/mcp-tools/config/Dockerfile",
    "K8S": "/Users/nolarose/mcp-tools/config/k8s-deployment.yaml",
    "SYSTEMD": "/Users/nolarose/mcp-tools/config/dashboard.service",
    "LOGROTATE": "/Users/nolarose/mcp-tools/config/logrotate-dashboard",
    "BACKUP_CRON": "/Users/nolarose/mcp-tools/config/backup-cron"
  },
  "LOGS": {
    "APPLICATION": "/Users/nolarose/mcp-tools/logs/dashboard.log",
    "ACCESS": "/Users/nolarose/mcp-tools/logs/access.log",
    "ERROR": "/Users/nolarose/mcp-tools/logs/error.log",
    "AUDIT": "/Users/nolarose/mcp-tools/logs/audit.log",
    "PERFORMANCE": "/Users/nolarose/mcp-tools/logs/performance.log",
    "BACKUP": "/Users/nolarose/mcp-tools/logs/backup.log",
    "WEBSOCKET": "/Users/nolarose/mcp-tools/logs/websocket.log"
  },
  "BACKUPS": {
    "DAILY": "/Users/nolarose/mcp-tools/backups/daily",
    "WEEKLY": "/Users/nolarose/mcp-tools/backups/weekly",
    "MONTHLY": "/Users/nolarose/mcp-tools/backups/monthly",
    "SNAPSHOTS": "/Users/nolarose/mcp-tools/backups/snapshots",
    "CONFIGS": "/Users/nolarose/mcp-tools/backups/configs"
  },
  "SNAPSHOTS": {
    "TENANT_A": "/Users/nolarose/mcp-tools/snapshots/tenant-a",
    "TENANT_B": "/Users/nolarose/mcp-tools/snapshots/tenant-b",
    "TENANT_C": "/Users/nolarose/mcp-tools/snapshots/tenant-c",
    "TEMP": "/Users/nolarose/mcp-tools/snapshots/temp",
    "ARCHIVE": "/Users/nolarose/mcp-tools/snapshots/archive"
  },
  "AUDIT": {
    "TENANT_A": "/Users/nolarose/mcp-tools/audit-review/tenant-a",
    "TENANT_B": "/Users/nolarose/mcp-tools/audit-review/tenant-b",
    "TENANT_C": "/Users/nolarose/mcp-tools/audit-review/tenant-c",
    "REPORTS": "/Users/nolarose/mcp-tools/audit-review/reports",
    "VIOLATIONS": "/Users/nolarose/mcp-tools/audit-review/violations"
  },
  "URLS": {
    "DEVELOPMENT": {
      "DASHBOARD": "http://localhost:3333/enhanced-dashboard.html",
      "API": "http://localhost:3333/api",
      "HEALTH": "http://localhost:3333/health",
      "METRICS": "http://localhost:3333/metrics",
      "WEBSOCKET": "ws://localhost:3333"
    },
    "STAGING": {
      "DASHBOARD": "https://staging.yourdomain.com/enhanced-dashboard.html",
      "API": "https://staging.yourdomain.com/api",
      "HEALTH": "https://staging.yourdomain.com/health",
      "METRICS": "https://staging.yourdomain.com/metrics",
      "WEBSOCKET": "wss://staging.yourdomain.com"
    },
    "PRODUCTION": {
      "DASHBOARD": "https://dashboard.yourdomain.com/enhanced-dashboard.html",
      "API": "https://dashboard.yourdomain.com/api",
      "HEALTH": "https://dashboard.yourdomain.com/health",
      "METRICS": "https://dashboard.yourdomain.com/metrics",
      "WEBSOCKET": "wss://dashboard.yourdomain.com"
    }
  },
  "PORTS": {
    "DEVELOPMENT": 3333,
    "STAGING": 3334,
    "PRODUCTION": 3335,
    "METRICS": 9090,
    "WEBSOCKET": 3333
  },
  "FILES": {
    "ENHANCED_DASHBOARD": "/Users/nolarose/mcp-tools/enhanced-dashboard.ts",
    "DASHBOARD_HTML": "/Users/nolarose/mcp-tools/enhanced-dashboard.html",
    "CLI": "/Users/nolarose/mcp-tools/dashboard-cli.ts",
    "DEPLOY": "/Users/nolarose/mcp-tools/deploy.ts",
    "TESTS": "/Users/nolarose/mcp-tools/test_suite.test.ts",
    "DEMO": "/Users/nolarose/mcp-tools/demo-complete-system.ts",
    "ANSI_UTILS": "/Users/nolarose/mcp-tools/ansi-utils.ts",
    "TABLE_UTILS": "/Users/nolarose/mcp-tools/table-utils.ts",
    "TENANT_ARCHIVER": "/Users/nolarose/mcp-tools/tenant-archiver.ts"
  },
  "BINARIES": {
    "BIN_DIR": "/Users/nolarose/mcp-tools/bin",
    "NODE_BIN": "/Users/nolarose/.bun/bin",
    "PYTHON_BIN": "/usr/bin/python3",
    "DOCKER_BIN": "/usr/local/bin/docker"
  },
  "SCRIPTS": {
    "SCRIPTS_DIR": "/Users/nolarose/mcp-tools/scripts",
    "DEPLOY_SCRIPT": "/Users/nolarose/mcp-tools/deploy.ts",
    "BACKUP_SCRIPT": "/Users/nolarose/mcp-tools/scripts/backup.sh",
    "RESTORE_SCRIPT": "/Users/nolarose/mcp-tools/scripts/restore.sh"
  }
};

// Environment-specific path getters
export function getPaths(environment: 'development' | 'staging' | 'production' = 'development') {
  return {
    database: PATHS.DATABASE[environment.toUpperCase() as keyof typeof PATHS.DATABASE],
    config: PATHS.CONFIG[environment.toUpperCase() as keyof typeof PATHS.CONFIG],
    urls: PATHS.URLS[environment.toUpperCase() as keyof typeof PATHS.URLS],
    port: PATHS.PORTS[environment.toUpperCase() as keyof typeof PATHS.PORTS]
  };
}

// Utility functions
export function ensureDirectoryExists(path: string): void {
  if (!require('fs').existsSync(path)) {
    require('fs').mkdirSync(path, { recursive: true });
  }
}

export function getLogPath(type: 'app' | 'access' | 'error' | 'audit' | 'performance'): string {
  const logMap = {
    app: PATHS.LOGS.APPLICATION,
    access: PATHS.LOGS.ACCESS,
    error: PATHS.LOGS.ERROR,
    audit: PATHS.LOGS.AUDIT,
    performance: PATHS.LOGS.PERFORMANCE
  };
  return logMap[type];
}

export function getSnapshotPath(tenant: string): string {
  return `${PATHS.SNAPSHOTS_DIR}/${tenant}`;
}

export function getAuditPath(tenant: string): string {
  return `${PATHS.AUDIT_DIR}/${tenant}`;
}
