import { readdir } from "node:fs/promises";

const profilesDir = "/Users/nolarose/Library/Application Support/Google/Chrome";

const entries = await readdir(profilesDir);
const profileDirs = entries.filter((e) => e.startsWith("Profile ") || e === "bun-apis-slides");

// Chrome color palette names
const colorNames: Record<number, string> = {
  0: "🔵 Blue",
  1: "🟣 Purple",
  2: "🟢 Green",
  3: "🟡 Yellow",
  4: "🟠 Orange",
  5: "🔴 Red",
  6: "🩷 Pink",
  7: "⚪ Grey",
  8: "🩵 Cyan",
};

// Get avatar info
function getAvatar(prefs: any): string {
  // Check for GAIA (Google account) picture
  if (prefs.profile?.gaia_info_picture_url) return "📷";

  // Check avatar_index
  const idx = prefs.profile?.avatar_index;
  if (idx !== undefined && idx >= 0 && idx <= 55) {
    // Modern Chrome avatars (abstract shapes/colors)
    if (idx <= 5) return "🔵";
    if (idx <= 11) return "🟢";
    if (idx <= 17) return "🟡";
    if (idx <= 23) return "🟠";
    if (idx <= 29) return "🔴";
    if (idx <= 35) return "🟣";
    if (idx <= 41) return "🩷";
    if (idx <= 47) return "⚪";
    return "🎨";
  }
  return "👤";
}

// Theme color to display
function getThemeColor(prefs: any): string {
  // Check user_color (newer Chrome)
  const userColor = prefs.browser?.theme?.user_color;
  if (userColor !== undefined) {
    // Convert to hex
    const hex = "#" + (userColor >>> 0).toString(16).padStart(8, "0").slice(2, 8);
    return hex.toUpperCase();
  }

  // Check color_variant
  const variant = prefs.browser?.theme?.color_variant;
  if (variant !== undefined) {
    return colorNames[variant] || `Variant ${variant}`;
  }

  // Check autogenerated theme
  const autoColor = prefs.autogenerated?.theme?.color;
  if (autoColor !== undefined) {
    return colorNames[autoColor] || `Color ${autoColor}`;
  }

  // Check for installed theme
  const themeId = prefs.extensions?.theme?.id;
  if (themeId) return "🎨 Custom";

  // Check NTP background
  if (prefs.ntp?.background_url) return "🖼️ Custom BG";

  return "⬜ Default";
}

// Get bookmark count
async function getBookmarkCount(profilePath: string): Promise<number> {
  const bookmarksPath = profilePath + "/Bookmarks";
  const file = Bun.file(bookmarksPath);

  if (await file.exists()) {
    try {
      const bookmarks = await file.json();
      let count = 0;

      function countBookmarks(node: any) {
        if (node.type === "url") count++;
        if (node.children) node.children.forEach(countBookmarks);
      }

      if (bookmarks.roots) {
        Object.values(bookmarks.roots).forEach(countBookmarks);
      }
      return count;
    } catch {
      return 0;
    }
  }
  return 0;
}

const profiles: Array<{
  "#": string;
  Directory: string;
  Avatar: string;
  Name: string;
  Email: string;
  Color: string;
  Bookmarks: number;
}> = [];

for (const entry of profileDirs) {
  const profilePath = profilesDir + "/" + entry;
  const prefPath = profilePath + "/Preferences";
  const file = Bun.file(prefPath);

  if (await file.exists()) {
    try {
      const prefs = await file.json();
      const bookmarkCount = await getBookmarkCount(profilePath);

      profiles.push({
        "#": entry.replace("Profile ", ""),
        Directory: entry,
        Avatar: getAvatar(prefs),
        Name: prefs.profile?.name || "Unknown",
        Email: prefs.account_info?.[0]?.email || "-",
        Color: getThemeColor(prefs),
        Bookmarks: bookmarkCount,
      });
    } catch {
      profiles.push({
        "#": entry.replace("Profile ", ""),
        Directory: entry,
        Avatar: "❓",
        Name: "Error reading",
        Email: "-",
        Color: "-",
        Bookmarks: 0,
      });
    }
  }
}

profiles.sort((a, b) => parseInt(a["#"]) - parseInt(b["#"]));

console.log("\n🌐 Chrome Profiles\n");
console.log(Bun.inspect.table(profiles, undefined, { colors: true }));
