#!/usr/bin/env bun

/**
 * Factory-Wager v4.0 Header Generator
 * Generates compliant markdown headers with SHA-256 integrity
 */

import { createHash } from 'crypto'

interface HeaderConfig {
  scope: string
  type: string
  title: string
  version?: string
  status?: string
  variant?: string
}

const SCOPES = ['GOV', 'SEC', 'OPS', 'ALERT', 'GIT', 'DATA', 'WS', 'TG', 'AI']
const TYPES = ['RULES', 'SUMMARY', 'STATS', 'FULL', 'TABLE', 'EXAMPLES', 'TEMPLATER', 'QUICKADD', 'AGENT']
const VARIANTS = ['EXPANDED', 'BASH', 'EXAMPLE', 'BUTTON', 'COMPRESSED']

function generateSHA256(content: string): string {
  return createHash('sha256').update(content).digest('hex')
}

function validateConfig(config: HeaderConfig): void {
  if (!SCOPES.includes(config.scope)) {
    throw new Error(`Invalid scope: ${config.scope}. Must be one of: ${SCOPES.join(', ')}`)
  }
  
  if (!TYPES.includes(config.type)) {
    throw new Error(`Invalid type: ${config.type}. Must be one of: ${TYPES.join(', ')}`)
  }
  
  if (config.variant && !VARIANTS.includes(config.variant)) {
    throw new Error(`Invalid variant: ${config.variant}. Must be one of: ${VARIANTS.join(', ')}`)
  }
}

function generateHeader(config: HeaderConfig): string {
  validateConfig(config)
  
  const version = config.version || 'v4.0'
  const status = config.status || 'ACTIVE'
  const variant = config.variant || 'EXPANDED'
  
  // Convert title to uppercase and replace spaces with dashes
  const titleId = config.title.toUpperCase().replace(/\s+/g, '-')
  
  // Generate the header content
  const headerContent = `${config.scope}-${config.type}-${titleId}-${version}-${variant}-${status}`
  const hash = generateSHA256(headerContent)
  
  // Factory-wager v4.0 format
  return `[${config.scope}-${config.type}-${titleId}-${version}-[${status}]-[${hash}]]`
}

function generateMarkdownStub(config: HeaderConfig): string {
  const header = generateHeader(config)
  const timestamp = new Date().toISOString()
  
  return `# ${header}

## Overview

${config.title} - ${config.type} rule for ${config.scope} scope.

## Configuration

- **Scope**: ${config.scope}
- **Type**: ${config.type}
- **Version**: ${config.version || 'v4.0'}
- **Status**: ${config.status || 'ACTIVE'}
- **Variant**: ${config.variant || 'EXPANDED'}
- **Generated**: ${timestamp}

## Implementation

<!-- TODO: Add implementation details -->

## Validation

- [ ] Hash integrity verified
- [ ] Schema validation passed
- [ ] AI scoring completed
- [ ] Peer review approved

---
*Generated by factory-wager v4.0 header generator*
`
}

// CLI interface
function parseArgs(): HeaderConfig {
  const args = process.argv.slice(2)
  const config: Partial<HeaderConfig> = {}
  
  for (let i = 0; i < args.length; i += 2) {
    const flag = args[i]
    const value = args[i + 1]
    
    switch (flag) {
      case '--scope':
        config.scope = value
        break
      case '--type':
        config.type = value
        break
      case '--title':
        config.title = value
        break
      case '--version':
        config.version = value
        break
      case '--status':
        config.status = value
        break
      case '--variant':
        config.variant = value
        break
    }
  }
  
  if (!config.scope || !config.type || !config.title) {
    console.error('❌ Missing required arguments')
    console.error('Usage: bun run templates/header-gen.js --scope <SCOPE> --type <TYPE> --title <TITLE> [options]')
    console.error('')
    console.error('Required:')
    console.error('  --scope    Scope: ' + SCOPES.join(', '))
    console.error('  --type     Type: ' + TYPES.join(', '))
    console.error('  --title    Title: Rule title (spaces allowed)')
    console.error('')
    console.error('Optional:')
    console.error('  --version  Version (default: v4.0)')
    console.error('  --status   Status (default: ACTIVE)')
    console.error('  --variant  Variant: ' + VARIANTS.join(', '))
    process.exit(1)
  }
  
  return config as HeaderConfig
}

// Main execution
function main() {
  try {
    const config = parseArgs()
    const markdown = generateMarkdownStub(config)
    
    console.log('🏭 Factory-Wager v4.0 Header Generator')
    console.log('=====================================')
    console.log()
    console.log(markdown)
    
    // Also output just the header for easy copying
    console.log()
    console.log('📋 Header Only:')
    console.log(generateHeader(config))
    
  } catch (error) {
    console.error('❌ Error:', error instanceof Error ? error.message : String(error))
    process.exit(1)
  }
}

// Run if executed directly
if (import.meta.main) {
  main()
}

export { generateHeader, generateMarkdownStub, type HeaderConfig }
